# Generated by Django 4.2 on 2023-10-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool_training', '0003_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Sach', 'Sach'), ('Tro Choi', 'Tro Choi'), ('Link MP3', 'Link MP3'), ('Link MP4', 'Link MP4')], max_length=50)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_training.month')),
                ('vocabularies', models.ManyToManyField(to='tool_training.vocabulary')),
            ],
        ),
    ]
