# Generated by Django 4.2 on 2023-10-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool_training', '0007_theory_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_training.exercise')),
                ('vocabularies', models.ManyToManyField(to='tool_training.vocabulary')),
            ],
        ),
    ]
