# Generated by Django 4.2 on 2023-10-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_training', '0008_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unknow',
        ),
    ]
