# Generated by Django 4.2 on 2023-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_training', '0016_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default='noUnit', max_length=100),
        ),
    ]
