# Generated by Django 4.2 on 2023-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_training', '0017_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='example',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
