# Generated by Django 4.2 on 2023-09-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên từ vựng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary_images/', verbose_name='Hình ảnh')),
                ('english_definition', models.TextField(verbose_name='Giải thích Anh-Anh')),
                ('english_to_vietnamese_definition', models.TextField(verbose_name='Giải thích Anh-Việt')),
            ],
            options={
                'verbose_name': 'Từ vựng',
                'verbose_name_plural': 'Từ vựng',
            },
        ),
    ]
