# Generated by Django 4.2 on 2023-10-08 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_document_group_remove_question_excercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(default='undefine', on_delete=django.db.models.deletion.CASCADE, to='web.exercise'),
        ),
    ]
