# Generated by Django 4.2 on 2023-10-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_question_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.exercise'),
        ),
    ]
