# Generated by Django 4.2 on 2023-10-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_question_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='vocabularies',
        ),
        migrations.RemoveField(
            model_name='month',
            name='group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vocabularies',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Theory',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
