# Generated by Django 4.2 on 2023-10-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
