# Generated by Django 4.2 on 2023-10-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_question_vocabularies_quest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
