# Generated by Django 4.2 on 2023-10-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_excercise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Noname',
        ),
    ]
