# Generated by Django 4.2 on 2023-10-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_excercise_noname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noname',
        ),
    ]
