# Generated by Django 4.2 on 2023-10-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên từ vựng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary_images/', verbose_name='Hình ảnh')),
                ('english_definition', models.TextField(verbose_name='Giải thích Anh-Anh')),
                ('english_to_vietnamese_definition', models.TextField(verbose_name='Giải thích Anh-Việt')),
                ('example', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Từ vựng',
                'verbose_name_plural': 'Từ vựng',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='insert-name', max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_training.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_training.group')),
            ],
        ),
    ]
