# Generated by Django 4.2 on 2023-10-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nobook', max_length=100)),
                ('document_type', models.CharField(choices=[('Sach', 'Sach'), ('Tro Choi', 'Tro Choi'), ('Link MP3', 'Link MP3'), ('Link MP4', 'Link MP4')], max_length=50)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_training.month')),
                ('vocabularies', models.ManyToManyField(to='web_training.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='insert-Unit', max_length=100)),
                ('number', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_training.document_type')),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_training.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_training.exercise')),
                ('vocabularies', models.ManyToManyField(to='web_training.vocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_training.unit'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='vocabularies',
            field=models.ManyToManyField(to='web_training.vocabulary'),
        ),
    ]
